### ISSUE TITLE
Stack trace when trying to provision a single machine

### ISSUE THREAD

**Issue by mattpep** [rakutentech/terraform-provider-vsphere#28]
Hi,

I get a stack trace when trying to provision a single machine.

Gist containing command output, crash.log and my config: https://gist.github.com/mattpep/05c80244a3ae47d71241
Version number: Terraform v0.6.1
Provider version: pre-release, SHA1 91f6716
(I get the same error output for the latest stable release, v0.3.1. Stack trace for that is https://gist.github.com/mattpep/33bb87b1fc627f8fd037)

To explain the setup:
I have a vCenter Server 5 Standard cluster which contains just one hypervisor host. It has numerous VMs on it. It is accessed via a VPN. The provision command is run from an Ubuntu 14.04 machine (itself built from the same image I'm trying to use for the VM) with 8G ram, 8G swap, 20G disk, and this machine has external internet access.

I originally thought this was an issue with the parent terraform project([this is the issue I raised](https://github.com/hashicorp/terraform/issues/2906)) but was directed here instead, hence re-raising the issue.

Thanks for any insight you can offer.

**Comment by tkak** [comment]
Thank you for your feedback. I guess this issue occurred  with our provider. In this case, the provider doesn't find a datastore path of vCenter. If you use only one datastore of vCenter, could you try to remove the datastore argument?

```
  disk {
    template = "template name"
  }
```

The provider selects a default datastore in case that the datastore argument is not specified.

And, if you use multiple datastores in your vCenter, it needs to specify datastore name.

**Comment by mattpep** [comment]
This was the cause, thanks. I'd made a mistake in the datastore name. Once that was corrected, I was able to create the VM.

**Comment by tkak** [comment]
Thanks! :ok_woman:
