### ISSUE TITLE
Connecting to vCenter that uses an unsigned certificate

### ISSUE THREAD

**Issue by davegallant** [rakutentech/terraform-provider-vsphere#55]
When I try to apply, I get this error:

`* Error setting up client: Post https://<ip address>/sdk: x509: cannot validate certificate for <ip address> because it doesn't contain any IP SANs`

Is there a way I can ignore certificate validation?

**Comment by escapenguin** [comment]
provider "vsphere" {
  user           = "${var.vsphere_user}"
  password       = "${var.vsphere_password}"
  vsphere_server = "${var.vsphere_server}"
  allow_unverified_ssl = "${var.allow_unverified_ssl}"
}

**Comment by superseb** [comment]
Check the builtin vsphere provider here https://www.terraform.io/docs/providers/vsphere/ and file issues under https://github.com/hashicorp/terraform/issues

**Comment by davegallant** [comment]
@escapenguin, allow_unverified_ssl works. Thanks.
