### ISSUE TITLE
Archive this project in favour of terraform-providers/terraform-provider-vsphere

### ISSUE THREAD

**Issue by ringods** [rakutentech/terraform-provider-vsphere#62]
Hello @tkak,

Would it be able to archive this project on Github? Still too much people seem to find this project, rather than the official provider at https://github.com/terraform-providers/terraform-provider-vsphere.

Please add a note in the README that this project has been archived.

**Comment by tkak** [comment]
Hi @ringods,

Thank you for your advice. I've updated the README.md.

I'm sorry for my long silence.
